# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/cad_veiculos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(775, 635)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(62, 132, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputNome = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNome.setEnabled(True)
        self.InputNome.setGeometry(QtCore.QRect(40, 100, 641, 41))
        self.InputNome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputNome.setReadOnly(True)
        self.InputNome.setObjectName("InputNome")
        self.BtnInserir = QtWidgets.QPushButton(self.centralwidget)
        self.BtnInserir.setGeometry(QtCore.QRect(280, 430, 231, 41))
        self.BtnInserir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnInserir.setStyleSheet("background-color:rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.BtnInserir.setObjectName("BtnInserir")
        self.InputMarca = QtWidgets.QLineEdit(self.centralwidget)
        self.InputMarca.setEnabled(True)
        self.InputMarca.setGeometry(QtCore.QRect(40, 280, 401, 41))
        self.InputMarca.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputMarca.setReadOnly(False)
        self.InputMarca.setObjectName("InputMarca")
        self.InputID = QtWidgets.QLineEdit(self.centralwidget)
        self.InputID.setEnabled(True)
        self.InputID.setGeometry(QtCore.QRect(40, 170, 641, 41))
        self.InputID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputID.setReadOnly(True)
        self.InputID.setObjectName("InputID")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 80, 161, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 150, 161, 17))
        self.label_6.setObjectName("label_6")
        self.InputModelo = QtWidgets.QLineEdit(self.centralwidget)
        self.InputModelo.setEnabled(True)
        self.InputModelo.setGeometry(QtCore.QRect(40, 340, 641, 41))
        self.InputModelo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputModelo.setReadOnly(False)
        self.InputModelo.setObjectName("InputModelo")
        self.InputAno = QtWidgets.QLineEdit(self.centralwidget)
        self.InputAno.setEnabled(True)
        self.InputAno.setGeometry(QtCore.QRect(510, 280, 171, 41))
        self.InputAno.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputAno.setReadOnly(False)
        self.InputAno.setObjectName("InputAno")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.InputNome, self.InputID)
        MainWindow.setTabOrder(self.InputID, self.InputMarca)
        MainWindow.setTabOrder(self.InputMarca, self.InputModelo)
        MainWindow.setTabOrder(self.InputModelo, self.InputAno)
        MainWindow.setTabOrder(self.InputAno, self.BtnInserir)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro de veículos"))
        self.InputNome.setPlaceholderText(_translate("MainWindow", "Nome do cliente"))
        self.BtnInserir.setText(_translate("MainWindow", "Inserir novo veículo"))
        self.InputMarca.setPlaceholderText(_translate("MainWindow", "Marca do veículo"))
        self.InputID.setPlaceholderText(_translate("MainWindow", "ID do cliente"))
        self.label_5.setText(_translate("MainWindow", "Nome do cliente"))
        self.label_6.setText(_translate("MainWindow", "ID do cliente"))
        self.InputModelo.setPlaceholderText(_translate("MainWindow", "Modelo do veículo"))
        self.InputAno.setInputMask(_translate("MainWindow", "9999"))
        self.InputAno.setPlaceholderText(_translate("MainWindow", "Ano do veículo"))
