# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/cad_clientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(775, 683)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(62, 132, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputNome = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNome.setEnabled(True)
        self.InputNome.setGeometry(QtCore.QRect(40, 130, 641, 41))
        self.InputNome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputNome.setReadOnly(False)
        self.InputNome.setObjectName("InputNome")
        self.BtnInserir = QtWidgets.QPushButton(self.centralwidget)
        self.BtnInserir.setGeometry(QtCore.QRect(220, 570, 231, 41))
        self.BtnInserir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnInserir.setStyleSheet("background-color:rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.BtnInserir.setObjectName("BtnInserir")
        self.InputCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.InputCPF.setGeometry(QtCore.QRect(40, 300, 311, 41))
        self.InputCPF.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputCPF.setReadOnly(False)
        self.InputCPF.setObjectName("InputCPF")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 270, 131, 17))
        self.label_4.setObjectName("label_4")
        self.InputEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.InputEmail.setEnabled(True)
        self.InputEmail.setGeometry(QtCore.QRect(40, 470, 641, 41))
        self.InputEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputEmail.setReadOnly(False)
        self.InputEmail.setObjectName("InputEmail")
        self.BtnGeraCPF = QtWidgets.QPushButton(self.centralwidget)
        self.BtnGeraCPF.setGeometry(QtCore.QRect(630, 30, 91, 41))
        self.BtnGeraCPF.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnGeraCPF.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(114, 159, 207);\n"
"border-radius: 10px;")
        self.BtnGeraCPF.setObjectName("BtnGeraCPF")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.InputNome, self.InputCPF)
        MainWindow.setTabOrder(self.InputCPF, self.InputEmail)
        MainWindow.setTabOrder(self.InputEmail, self.BtnInserir)
        MainWindow.setTabOrder(self.BtnInserir, self.BtnGeraCPF)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Cadastro de clientes"))
        self.InputNome.setPlaceholderText(_translate("MainWindow", "Nome do cliente"))
        self.BtnInserir.setText(_translate("MainWindow", "Inserir novo cliente"))
        self.InputCPF.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.InputCPF.setPlaceholderText(_translate("MainWindow", "Numero do Celular com DDD"))
        self.label_4.setText(_translate("MainWindow", "CPF"))
        self.InputEmail.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.BtnGeraCPF.setText(_translate("MainWindow", "Gera CPF"))
