# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/manut_clientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(775, 683)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(62, 132, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputNome = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNome.setEnabled(True)
        self.InputNome.setGeometry(QtCore.QRect(40, 130, 641, 41))
        self.InputNome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputNome.setReadOnly(False)
        self.InputNome.setObjectName("InputNome")
        self.BtnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCancelar.setGeometry(QtCore.QRect(270, 340, 231, 41))
        self.BtnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnCancelar.setStyleSheet("background-color: rgb(245, 121, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.BtnCancelar.setObjectName("BtnCancelar")
        self.InputCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.InputCPF.setEnabled(False)
        self.InputCPF.setGeometry(QtCore.QRect(40, 60, 311, 41))
        self.InputCPF.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputCPF.setReadOnly(True)
        self.InputCPF.setObjectName("InputCPF")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 30, 131, 17))
        self.label_4.setObjectName("label_4")
        self.InputEmail = QtWidgets.QLineEdit(self.centralwidget)
        self.InputEmail.setEnabled(True)
        self.InputEmail.setGeometry(QtCore.QRect(40, 200, 641, 41))
        self.InputEmail.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputEmail.setReadOnly(False)
        self.InputEmail.setObjectName("InputEmail")
        self.BtnExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.BtnExcluir.setGeometry(QtCore.QRect(520, 340, 231, 41))
        self.BtnExcluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnExcluir.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);\n"
"border-radius: 10px;")
        self.BtnExcluir.setObjectName("BtnExcluir")
        self.BtnConfirmar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnConfirmar.setGeometry(QtCore.QRect(30, 340, 231, 41))
        self.BtnConfirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnConfirmar.setStyleSheet("background-color:rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.BtnConfirmar.setObjectName("BtnConfirmar")
        self.InputID = QtWidgets.QLineEdit(self.centralwidget)
        self.InputID.setEnabled(False)
        self.InputID.setGeometry(QtCore.QRect(390, 60, 291, 41))
        self.InputID.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputID.setReadOnly(True)
        self.InputID.setObjectName("InputID")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(400, 30, 131, 17))
        self.label_5.setObjectName("label_5")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.InputCPF, self.InputID)
        MainWindow.setTabOrder(self.InputID, self.InputNome)
        MainWindow.setTabOrder(self.InputNome, self.InputEmail)
        MainWindow.setTabOrder(self.InputEmail, self.BtnConfirmar)
        MainWindow.setTabOrder(self.BtnConfirmar, self.BtnCancelar)
        MainWindow.setTabOrder(self.BtnCancelar, self.BtnExcluir)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Manutenção de clientes"))
        self.InputNome.setPlaceholderText(_translate("MainWindow", "Nome do cliente"))
        self.BtnCancelar.setText(_translate("MainWindow", "Cancelar/sair"))
        self.InputCPF.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.InputCPF.setPlaceholderText(_translate("MainWindow", "Numero do Celular com DDD"))
        self.label_4.setText(_translate("MainWindow", "CPF"))
        self.InputEmail.setPlaceholderText(_translate("MainWindow", "E-mail"))
        self.BtnExcluir.setText(_translate("MainWindow", "Excluir cliente"))
        self.BtnConfirmar.setText(_translate("MainWindow", "Alterar cliente"))
        self.InputID.setPlaceholderText(_translate("MainWindow", "Nome do cliente"))
        self.label_5.setText(_translate("MainWindow", "ID do cliente"))
