# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/manut_veiculos.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(775, 635)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setMouseTracking(True)
        MainWindow.setStyleSheet("background-color: rgb(62, 132, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputNome = QtWidgets.QLineEdit(self.centralwidget)
        self.InputNome.setEnabled(False)
        self.InputNome.setGeometry(QtCore.QRect(40, 100, 641, 41))
        self.InputNome.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputNome.setReadOnly(True)
        self.InputNome.setObjectName("InputNome")
        self.BtnConfirmar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnConfirmar.setGeometry(QtCore.QRect(40, 510, 231, 41))
        self.BtnConfirmar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnConfirmar.setStyleSheet("background-color:rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.BtnConfirmar.setObjectName("BtnConfirmar")
        self.InputMarca = QtWidgets.QLineEdit(self.centralwidget)
        self.InputMarca.setEnabled(True)
        self.InputMarca.setGeometry(QtCore.QRect(230, 250, 451, 41))
        self.InputMarca.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputMarca.setReadOnly(False)
        self.InputMarca.setObjectName("InputMarca")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 80, 161, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 150, 161, 17))
        self.label_6.setObjectName("label_6")
        self.InputModelo = QtWidgets.QLineEdit(self.centralwidget)
        self.InputModelo.setEnabled(True)
        self.InputModelo.setGeometry(QtCore.QRect(40, 320, 461, 41))
        self.InputModelo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputModelo.setReadOnly(False)
        self.InputModelo.setObjectName("InputModelo")
        self.InputAno = QtWidgets.QLineEdit(self.centralwidget)
        self.InputAno.setEnabled(True)
        self.InputAno.setGeometry(QtCore.QRect(510, 320, 171, 41))
        self.InputAno.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputAno.setReadOnly(False)
        self.InputAno.setObjectName("InputAno")
        self.BtnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCancelar.setGeometry(QtCore.QRect(290, 510, 231, 41))
        self.BtnCancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnCancelar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(245, 121, 0);\n"
"border-radius: 10px;")
        self.BtnCancelar.setObjectName("BtnCancelar")
        self.BtnExcluir = QtWidgets.QPushButton(self.centralwidget)
        self.BtnExcluir.setGeometry(QtCore.QRect(530, 510, 231, 41))
        self.BtnExcluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BtnExcluir.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(239, 41, 41);\n"
"border-radius: 10px;")
        self.BtnExcluir.setObjectName("BtnExcluir")
        self.InputCPF = QtWidgets.QLineEdit(self.centralwidget)
        self.InputCPF.setEnabled(False)
        self.InputCPF.setGeometry(QtCore.QRect(40, 170, 311, 41))
        self.InputCPF.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputCPF.setReadOnly(True)
        self.InputCPF.setObjectName("InputCPF")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 230, 161, 17))
        self.label_7.setObjectName("label_7")
        self.InputIDVeiculo = QtWidgets.QLineEdit(self.centralwidget)
        self.InputIDVeiculo.setEnabled(False)
        self.InputIDVeiculo.setGeometry(QtCore.QRect(40, 250, 141, 41))
        self.InputIDVeiculo.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);\n"
"")
        self.InputIDVeiculo.setReadOnly(True)
        self.InputIDVeiculo.setObjectName("InputIDVeiculo")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.InputNome, self.InputCPF)
        MainWindow.setTabOrder(self.InputCPF, self.InputIDVeiculo)
        MainWindow.setTabOrder(self.InputIDVeiculo, self.InputMarca)
        MainWindow.setTabOrder(self.InputMarca, self.InputModelo)
        MainWindow.setTabOrder(self.InputModelo, self.InputAno)
        MainWindow.setTabOrder(self.InputAno, self.BtnConfirmar)
        MainWindow.setTabOrder(self.BtnConfirmar, self.BtnCancelar)
        MainWindow.setTabOrder(self.BtnCancelar, self.BtnExcluir)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Alteração/Exclusão de veículos"))
        self.InputNome.setPlaceholderText(_translate("MainWindow", "Nome do cliente"))
        self.BtnConfirmar.setText(_translate("MainWindow", "Confirmar alteração"))
        self.InputMarca.setPlaceholderText(_translate("MainWindow", "Marca do veículo"))
        self.label_5.setText(_translate("MainWindow", "Nome do cliente"))
        self.label_6.setText(_translate("MainWindow", "CPF do cliente"))
        self.InputModelo.setPlaceholderText(_translate("MainWindow", "Modelo do veículo"))
        self.InputAno.setInputMask(_translate("MainWindow", "9999"))
        self.InputAno.setPlaceholderText(_translate("MainWindow", "Ano do veículo"))
        self.BtnCancelar.setText(_translate("MainWindow", "Cancelar/Sair"))
        self.BtnExcluir.setText(_translate("MainWindow", "Excluir veículo"))
        self.InputCPF.setInputMask(_translate("MainWindow", "000.000.000-00"))
        self.InputCPF.setPlaceholderText(_translate("MainWindow", "Numero do Celular com DDD"))
        self.label_7.setText(_translate("MainWindow", "ID do veículo"))
        self.InputIDVeiculo.setPlaceholderText(_translate("MainWindow", "ID do veículo"))
