# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/permissoes_usuarios.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(636, 651)
        MainWindow.setStyleSheet("background-color: rgb(62, 132, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.InputUsuario.setGeometry(QtCore.QRect(230, 140, 221, 41))
        self.InputUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);")
        self.InputUsuario.setReadOnly(True)
        self.InputUsuario.setObjectName("InputUsuario")
        self.BtnSetar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnSetar.setGeometry(QtCore.QRect(220, 500, 231, 41))
        self.BtnSetar.setStyleSheet("background-color:rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.BtnSetar.setObjectName("BtnSetar")
        self.IconeUsuario = QtWidgets.QLabel(self.centralwidget)
        self.IconeUsuario.setGeometry(QtCore.QRect(140, 120, 71, 81))
        self.IconeUsuario.setText("")
        self.IconeUsuario.setPixmap(QtGui.QPixmap("/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/../GIT/HELLLO_WORLD/icone_usuario.png"))
        self.IconeUsuario.setObjectName("IconeUsuario")
        self.BtnCancelar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCancelar.setGeometry(QtCore.QRect(220, 570, 231, 41))
        self.BtnCancelar.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(245, 121, 0);\n"
"border-radius: 10px;")
        self.BtnCancelar.setObjectName("BtnCancelar")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(115, 210, 22);")
        self.label.setObjectName("label")
        self.CbCriar = QtWidgets.QCheckBox(self.centralwidget)
        self.CbCriar.setGeometry(QtCore.QRect(170, 270, 110, 28))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.CbCriar.setFont(font)
        self.CbCriar.setObjectName("CbCriar")
        self.CbEditar = QtWidgets.QCheckBox(self.centralwidget)
        self.CbEditar.setGeometry(QtCore.QRect(170, 310, 110, 28))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.CbEditar.setFont(font)
        self.CbEditar.setObjectName("CbEditar")
        self.CbExcluir = QtWidgets.QCheckBox(self.centralwidget)
        self.CbExcluir.setGeometry(QtCore.QRect(170, 350, 110, 28))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.CbExcluir.setFont(font)
        self.CbExcluir.setObjectName("CbExcluir")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 230, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.CbRoot = QtWidgets.QCheckBox(self.centralwidget)
        self.CbRoot.setGeometry(QtCore.QRect(170, 390, 161, 28))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        self.CbRoot.setFont(font)
        self.CbRoot.setObjectName("CbRoot")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.InputUsuario, self.BtnSetar)
        MainWindow.setTabOrder(self.BtnSetar, self.BtnCancelar)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela de permissões"))
        self.InputUsuario.setPlaceholderText(_translate("MainWindow", "Usuário:"))
        self.BtnSetar.setText(_translate("MainWindow", "Setar permissões"))
        self.BtnCancelar.setText(_translate("MainWindow", "Cancelar"))
        self.label.setText(_translate("MainWindow", "Cadastro de permissões a usuário"))
        self.CbCriar.setText(_translate("MainWindow", "Criar"))
        self.CbEditar.setText(_translate("MainWindow", "Editar"))
        self.CbExcluir.setText(_translate("MainWindow", "Excluir"))
        self.label_2.setText(_translate("MainWindow", "Permissões:"))
        self.CbRoot.setText(_translate("MainWindow", "Root"))
