# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/tela_clientes.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.setEnabled(True)
        MainWindow.resize(843, 525)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(62, 132, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TabelaClientes = QtWidgets.QTableWidget(self.centralwidget)
        self.TabelaClientes.setEnabled(True)
        self.TabelaClientes.setGeometry(QtCore.QRect(10, 80, 821, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.TabelaClientes.sizePolicy().hasHeightForWidth())
        self.TabelaClientes.setSizePolicy(sizePolicy)
        self.TabelaClientes.setMinimumSize(QtCore.QSize(465, 0))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.TabelaClientes.setFont(font)
        self.TabelaClientes.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(138, 226, 52);")
        self.TabelaClientes.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.TabelaClientes.setObjectName("TabelaClientes")
        self.TabelaClientes.setColumnCount(4)
        self.TabelaClientes.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(17)
        item.setFont(font)
        self.TabelaClientes.setHorizontalHeaderItem(3, item)
        self.TabelaClientes.horizontalHeader().setDefaultSectionSize(150)
        self.TabelaClientes.horizontalHeader().setSortIndicatorShown(True)
        self.TabelaClientes.horizontalHeader().setStretchLastSection(True)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 781, 61))
        font = QtGui.QFont()
        font.setPointSize(17)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Clientes"))
        item = self.TabelaClientes.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ID"))
        item = self.TabelaClientes.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nome"))
        item = self.TabelaClientes.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "CPF"))
        item = self.TabelaClientes.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "E-mail"))
        self.label.setText(_translate("MainWindow", "Dê um duplo clique em um cliente para selecionar o cliente"))
