# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/tela_cadastro.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModal)
        MainWindow.resize(636, 651)
        MainWindow.setStyleSheet("background-color: rgb(62, 132, 238);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.InputUsuario = QtWidgets.QLineEdit(self.centralwidget)
        self.InputUsuario.setGeometry(QtCore.QRect(230, 140, 221, 41))
        self.InputUsuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);")
        self.InputUsuario.setObjectName("InputUsuario")
        self.InputSenha = QtWidgets.QLineEdit(self.centralwidget)
        self.InputSenha.setGeometry(QtCore.QRect(230, 230, 221, 41))
        self.InputSenha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);")
        self.InputSenha.setInputMask("")
        self.InputSenha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.InputSenha.setObjectName("InputSenha")
        self.BtnCadastrar = QtWidgets.QPushButton(self.centralwidget)
        self.BtnCadastrar.setGeometry(QtCore.QRect(220, 500, 231, 41))
        self.BtnCadastrar.setStyleSheet("background-color:rgb(78, 154, 6);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 10px;")
        self.BtnCadastrar.setObjectName("BtnCadastrar")
        self.IconeUsuario = QtWidgets.QLabel(self.centralwidget)
        self.IconeUsuario.setGeometry(QtCore.QRect(140, 120, 71, 81))
        self.IconeUsuario.setText("")
        self.IconeUsuario.setPixmap(QtGui.QPixmap("/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/../GIT/HELLLO_WORLD/icone_usuario.png"))
        self.IconeUsuario.setObjectName("IconeUsuario")
        self.IconeSenha = QtWidgets.QLabel(self.centralwidget)
        self.IconeSenha.setGeometry(QtCore.QRect(140, 210, 71, 81))
        self.IconeSenha.setText("")
        self.IconeSenha.setPixmap(QtGui.QPixmap("/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/../GIT/HELLLO_WORLD/icone_senha.png"))
        self.IconeSenha.setObjectName("IconeSenha")
        self.BtnLogin = QtWidgets.QPushButton(self.centralwidget)
        self.BtnLogin.setGeometry(QtCore.QRect(220, 570, 231, 41))
        self.BtnLogin.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(245, 121, 0);\n"
"border-radius: 10px;")
        self.BtnLogin.setObjectName("BtnLogin")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 20, 481, 51))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(115, 210, 22);")
        self.label.setObjectName("label")
        self.InputConfirmar = QtWidgets.QLineEdit(self.centralwidget)
        self.InputConfirmar.setGeometry(QtCore.QRect(230, 310, 221, 41))
        self.InputConfirmar.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius: 10px;\n"
"border-color: rgb(0,0,0);")
        self.InputConfirmar.setInputMask("")
        self.InputConfirmar.setEchoMode(QtWidgets.QLineEdit.Password)
        self.InputConfirmar.setObjectName("InputConfirmar")
        self.IconeSenha_2 = QtWidgets.QLabel(self.centralwidget)
        self.IconeSenha_2.setGeometry(QtCore.QRect(140, 290, 71, 81))
        self.IconeSenha_2.setText("")
        self.IconeSenha_2.setPixmap(QtGui.QPixmap("/home/joao-vitor/Dropbox/JP 2021/PROJETO OFICINA/../GIT/HELLLO_WORLD/icone_senha.png"))
        self.IconeSenha_2.setObjectName("IconeSenha_2")
        self.CbCriar = QtWidgets.QCheckBox(self.centralwidget)
        self.CbCriar.setGeometry(QtCore.QRect(170, 410, 110, 28))
        self.CbCriar.setObjectName("CbCriar")
        self.CbEditar = QtWidgets.QCheckBox(self.centralwidget)
        self.CbEditar.setGeometry(QtCore.QRect(280, 410, 110, 28))
        self.CbEditar.setObjectName("CbEditar")
        self.CbExcluir = QtWidgets.QCheckBox(self.centralwidget)
        self.CbExcluir.setGeometry(QtCore.QRect(400, 410, 110, 28))
        self.CbExcluir.setObjectName("CbExcluir")
        self.CbRoot = QtWidgets.QCheckBox(self.centralwidget)
        self.CbRoot.setGeometry(QtCore.QRect(270, 450, 161, 28))
        self.CbRoot.setObjectName("CbRoot")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.InputUsuario, self.InputSenha)
        MainWindow.setTabOrder(self.InputSenha, self.InputConfirmar)
        MainWindow.setTabOrder(self.InputConfirmar, self.BtnCadastrar)
        MainWindow.setTabOrder(self.BtnCadastrar, self.BtnLogin)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Tela de cadastro"))
        self.InputUsuario.setPlaceholderText(_translate("MainWindow", "Usuário:"))
        self.InputSenha.setPlaceholderText(_translate("MainWindow", "Senha:"))
        self.BtnCadastrar.setText(_translate("MainWindow", "Cadastrar"))
        self.BtnLogin.setText(_translate("MainWindow", "Fazer Login"))
        self.label.setText(_translate("MainWindow", "Cadastro de novo usuário:"))
        self.InputConfirmar.setPlaceholderText(_translate("MainWindow", "Confirme a senha:"))
        self.CbCriar.setText(_translate("MainWindow", "Criar"))
        self.CbEditar.setText(_translate("MainWindow", "Editar"))
        self.CbExcluir.setText(_translate("MainWindow", "Excluir"))
        self.CbRoot.setText(_translate("MainWindow", "Administrador"))
